# Map Engine Unit Test Makefile

OPENSNES ?= $(error Set OPENSNES env var)
TARGET   := test_map.sfc
ROM_NAME := MAP TESTS

CSRC     := test_map.c
USE_LIB  := 1
LIB_MODULES := console map sprite dma background text debug

include $(OPENSNES)/make/common.mk
