# HDMA Unit Test Makefile

OPENSNES ?= $(error Set OPENSNES env var)
TARGET   := test_hdma.sfc
ROM_NAME := HDMA TESTS

CSRC     := test_hdma.c
USE_LIB  := 1
LIB_MODULES := console hdma dma text sprite math

include $(OPENSNES)/make/common.mk
