OPENSNES ?= $(error Set OPENSNES env var)
TARGET   := test_math.sfc
ROM_NAME := MATH TESTS

CSRC     := test_math.c
USE_LIB  := 1
LIB_MODULES := console math text sprite dma

include $(OPENSNES)/make/common.mk
