# Mouse Unit Test Makefile

OPENSNES ?= $(error Set OPENSNES env var)
TARGET   := test_mouse.sfc
ROM_NAME := MOUSE TESTS

CSRC     := test_mouse.c
USE_LIB  := 1
LIB_MODULES := console input text sprite dma

include $(OPENSNES)/make/common.mk
