# Mode 7 Unit Test Makefile

OPENSNES ?= $(error Set OPENSNES env var)
TARGET   := test_mode7.sfc
ROM_NAME := MODE7 TESTS

CSRC     := test_mode7.c
USE_LIB  := 1
LIB_MODULES := console mode7 math dma text sprite

include $(OPENSNES)/make/common.mk
