# Debug Module Unit Test Makefile

OPENSNES ?= $(error Set OPENSNES env var)
TARGET   := test_debug.sfc
ROM_NAME := DEBUG TESTS

CSRC     := test_debug.c
USE_LIB  := 1
LIB_MODULES := console sprite dma text debug

include $(OPENSNES)/make/common.mk
