# LZSS Unit Test Makefile

OPENSNES ?= $(error Set OPENSNES env var)
TARGET   := test_lzss.sfc
ROM_NAME := LZSS TESTS

CSRC     := test_lzss.c
USE_LIB  := 1
LIB_MODULES := console lzss text sprite dma

include $(OPENSNES)/make/common.mk
