# Window Unit Test Makefile

OPENSNES ?= $(error Set OPENSNES env var)
TARGET   := test_window.sfc
ROM_NAME := WINDOW TESTS

CSRC     := test_window.c
USE_LIB  := 1
LIB_MODULES := console window dma text sprite

include $(OPENSNES)/make/common.mk
