# Mosaic Unit Test Makefile

OPENSNES ?= $(error Set OPENSNES env var)
TARGET   := test_mosaic.sfc
ROM_NAME := MOSAIC TESTS

CSRC     := test_mosaic.c
USE_LIB  := 1
LIB_MODULES := console mosaic dma text sprite

include $(OPENSNES)/make/common.mk
