# Sprite Unit Test Makefile

OPENSNES ?= $(error Set OPENSNES env var)
TARGET   := test_sprite.sfc
ROM_NAME := SPRITE TESTS

CSRC     := test_sprite.c
USE_LIB  := 1
LIB_MODULES := console sprite sprite_dynamic sprite_lut dma text

include $(OPENSNES)/make/common.mk
