# Console Unit Test Makefile

OPENSNES ?= $(error Set OPENSNES env var)
TARGET   := test_console.sfc
ROM_NAME := CONSOLE TESTS

CSRC     := test_console.c
USE_LIB  := 1
LIB_MODULES := console dma text sprite

include $(OPENSNES)/make/common.mk
