# DMA Unit Test Makefile

OPENSNES ?= $(error Set OPENSNES env var)
TARGET   := test_dma.sfc
ROM_NAME := DMA TESTS

CSRC     := test_dma.c
USE_LIB  := 1
LIB_MODULES := console dma text sprite

include $(OPENSNES)/make/common.mk
