OPENSNES ?= $(error Set OPENSNES env var)
TARGET   := test_collision.sfc
ROM_NAME := COLL TESTS

CSRC     := test_collision.c
USE_LIB  := 1
LIB_MODULES := console collision text sprite dma

include $(OPENSNES)/make/common.mk
