OPENSNES ?= $(error Set OPENSNES env var)
TARGET   := test_animation.sfc
ROM_NAME := ANIM TESTS

CSRC     := test_animation.c
USE_LIB  := 1
LIB_MODULES := console animation text sprite dma

include $(OPENSNES)/make/common.mk
