# Types Unit Test Makefile

OPENSNES ?= $(error Set OPENSNES env var)
TARGET   := test_types.sfc
ROM_NAME := TYPE TESTS

CSRC     := test_types.c
USE_LIB  := 1
LIB_MODULES := console text dma sprite

include $(OPENSNES)/make/common.mk
