# Input Unit Test Makefile

OPENSNES ?= $(error Set OPENSNES env var)
TARGET   := test_input.sfc
ROM_NAME := INPUT TESTS

CSRC     := test_input.c
USE_LIB  := 1
LIB_MODULES := console input text sprite dma

include $(OPENSNES)/make/common.mk
