# Color Math Unit Test Makefile

OPENSNES ?= $(error Set OPENSNES env var)
TARGET   := test_colormath.sfc
ROM_NAME := COLORMATH TESTS

CSRC     := test_colormath.c
USE_LIB  := 1
LIB_MODULES := console colormath dma text sprite

include $(OPENSNES)/make/common.mk
