# Background Unit Test Makefile

OPENSNES ?= $(error Set OPENSNES env var)
TARGET   := test_background.sfc
ROM_NAME := BG TESTS

CSRC     := test_background.c
USE_LIB  := 1
LIB_MODULES := console background dma text sprite

include $(OPENSNES)/make/common.mk
